--Planilha/Tabela: Estudante
CREATE TABLE ESTUDANTE(
	ID SERIAL PRIMARY KEY, -- COLUNA DE IDENTIFICAÇÃO
	NOME VARCHAR(100), -- VARCHAR O TAMANHO É VARIÁVEL
	MATRICULA CHAR(10), -- CHAR O TAMANHO É FIXO
	CURSO VARCAHR(50), 
	LOGIN VARCHAR(20), 
	SENHA VARCHAR(15),
	DATA_NASCIMENTO DATE -- RECEBE DATAS NO FORMATO YYYY-MM-DD
);

--Planilha/Tabela: Docente
CREATE TABLE DOCENTE (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100),
	MATRICULA CHAR(7),
	UNIDADE_CURRICULAR VARCHAR(20),
	LOGIN VARCHAR(20),
	SENHA VARCHAR(15),
	DATA_NASCIMENTO DATE
);
