CREATE DATABASE BIBLIOTECA;
CREATE TABLE LIVRO(
ID SERIAL PRIMARY KEY,
TITULO VARCHAR (100),
AUTOR VARCHAR (50),
EDITORA VARCHAR(20),
GENERO VARCHAR(115),
ESTADO_CONSEVACAO VARCHAR(50),
QUANTIDADE_COPIAS INT
);

CREATE TABLE PESSOAS(
ID SERIAL PRIMARY KEY,
NOME_COMPLETO VARCHAR (100),
MATRICULA VARCHAR (10),
EMAIL VARCHAR (50), 
TELEFONE VARCHAR(14) -- (24)99294-0839
);

CREATE TABLE EMPRESTIMO(
ID SERIAL PRIMARY KEY,
DATA_RETIRADA TIMESTAMP,
DATA_DDEVOLUCAO TIMESTAMP,
ESTADO_CONSEVACAO VARCHAR(50)
);

ALTER TABLE EMPRESTIMO add column ID_LIVRO INT;
alter table EMPRESTIMO add foreign key (ID_LIVRO) references LIVRO(ID);

ALTER table EMPRESTIMO add column ID_PESSOA INT;
alter table EMPRESTIMO add foreign key (ID_PESSOA) references PESSOAS(ID);


ALTER TABLE PESSOAS add column ID_EMPRESTIMO INT;
alter table PESSOAS add foreign key (ID_EMPRESTIMO) references EMPRESTIMO(ID);

ALTER TABLE EMPRESTIMO DROP COLUMN ID_LIVRO;
ALTER TABLE LIVRO DROP COLUMN ID_PESSOA;
ALTER TABLE PESSOAS DROP COLUMN ID_EMPRESTIMO;