CREATE TABLE LIVRO(
ID SERIAL PRIMARY KEY,
TITULO VARCHAR (100),
AUTOR VARCHAR (50),
EDITORA VARCHAR(20),
GENERO VARCHAR(115),
ESTADO_CONSEVACAO VARCHAR(50),
QUANTIDADE_COPIAS INT
);

CREATE TABLE PESSOAS(
ID SERIAL PRIMARY KEY,
NOME_COMPLETO VARCHAR (100),
MATRICULA VARCAHR (10),
EMAIL VARCHAR (50), 
TELEFONE VARCHAR(14) -- (24)99294-0839
);

CREATE TABLE EMPRESTIMO(
ID SERIAL PRIMARY KEY,
DATA_RETIRADA TIMESTAMP,
DATA_DDEVOLUCAO TIMESTAMP,
ESTADO_CONSEVACAO VARCHAR(50)
);