CREATE TABLE PRODUTO(
ID SERIAL PRIMARY KEY,
NOME VARCHAR (30)
TAMANHO VARCHAR(3),
COR VARCHAR(10),
QUANT_DISP VARCHAR(250),
PRECO_UND NUMERIC (6,2) -- NUMERIC (6,2) ONDE 6 E A SOMA DO TOTAL DOS NUMEROS ANTES DA VIRGULA COM A QUANTIDADE DOS NUMEROS DEPOIS DA VIRGLA
);

CREATE TABLE CATEGORIA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR (30)
);

CREATE TABLE CLIENTES(
ID SERIAL PRIMARY KEY,
NOME VARCHAR (100),
EMAIL VARCHAR (50),
TELEFONE VARCHAR (14)
);

CREATE TABLE VENDAS(
ID SERIAL PRIMARY KEY,
DATA_HORA TIMESTAMP,
FORMA_PAGAMENTO VARCHAR (10),
-- PRODUTO
-- ATENDENDE
);

CREATE TABLE ATENDENTES (
ID SERIAL PRIMARY KEY,
NOME VARCHAR (100),
CPF CHAR (11)

);