CREATE TABLE ANIMAL(
ID SERIAL PRIMARY KEY,
ESPECIE VARCHAR (20),
RACA VARCHAR (20),
IDADE INT,
INFO_MEDICAS TEXT
);

CREATE TABLE DONO(
ID SERIAL,
NOME_COMPLETO VARCHAR(100) ,
CPF CAHAR (14),
TELEFONE VARCHAR (14)
);

CREATE TABLE CONSULTA(
DATA_HORA TIMESTAMP,
-- ANIMAL VARCHAR (100),
-- VETERINARIO VARCHAR (50),
OBS_MEDICAS TEXT
);

CREATE TABLE VETERINARIO(
ID SERIAL PRIMARY KEY,
NOME VARCHAR (100)
CRMV CHAR (13),
ESPECILAZACAO TEXT,
JORNADA_DIARIA_HORAS INT  
);

CREATE TABLE ENDERECO(
ID SERIAL PRIMARY,
CEP CHAR (9),
LOGRADOURO VARCHAR (100),
LACALIDADE(50),
COMPLEMENTO VARCHAR(255),
NUMERO INT,
BAIRRO VARCHAR (50),
UF CHAR (2),
REFERENCIA VARCHAR (255)
);